# Generated by Django 5.1.6 on 2025-02-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_tokenmodel_user2_remove_movie_actor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
